Enable infra stage on main branch

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -140,8 +140,42 @@ jobs:
     steps:
       # Checkout code from git
       - checkout
-      - aws-cli/setup
-           
+      - aws-cli/setup:
+          aws-access-key-id: PARAM_AWS_CLI_ACCESS_KEY_ID
+          aws-secret-access-key: PARAM_AWS_CLI_SECRET_ACCESS_KEY
+          aws-region: PARAM_AWS_CLI_REGION
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            echo $PARAM_AWS_CLI_ACCESS_KEY_ID
+            echo $PARAM_AWS_CLI_SECRET_ACCESS_KEY
+            aws cloudformation deploy \
+              --region us-east-1 \
+              --template-file .circleci/files/backend.yml \
+              --tags project=prj3-hnguyen3 \
+              --stack-name "prj3-hnguyen3-back-end" \
+              --parameter-overrides ID="prj3-hnguyen3"                
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            echo $PARAM_AWS_CLI_ACCESS_KEY_ID
+            echo $PARAM_AWS_CLI_SECRET_ACCESS_KEY
+            aws cloudformation deploy \
+              --region us-east-1 \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=yprj3-hnguyen3 \
+              --stack-name "prj3-hnguyen3-front-end" \
+              --parameter-overrides ID="prj3-hnguyen3"  
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            # Your code here
+            exit 1
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      # Here's where you will add some code to rollback on failure      
 
   configure-infrastructure:
     executor:
