change

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,8 +1,10 @@
 version: 2.1
+
 commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    parameters: null
+    parameters:
+      # Add parameter here   
     steps:
       - run:
           name: Destroy environments
@@ -12,29 +14,23 @@ commands:
             # exit 1
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
-    parameters: null
+    parameters:
+      # Add parameter here     
     steps:
       - run:
           name: Revert migrations
-          command: >
-            # Curl command here to see if there was a successful migration
-            associated with the workflow id, store result in SUCCESS variable
-
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
             SUCCESS = 1
-
             if(( $SUCCESS==1 )); 
-
             then
-
             #  cd ~/project/backend
-
             #  npm install
-
             #  Add revert code here. You can find this in the Getting Started section.
-
             #  exit 1
-
             fi
+            
 jobs:
   build-frontend:
     docker:
@@ -42,8 +38,7 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys:
-            - frontend-build
+          keys: [frontend-build]
       - run:
           name: Build front-end
           command: |
@@ -52,8 +47,7 @@ jobs:
             pwd
             ls
       - save_cache:
-          paths:
-            - frontend/node_modules
+          paths: [frontend/node_modules]
           key: frontend-build
   build-backend:
     docker:
@@ -61,37 +55,48 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys:
-            - backend-build
+          keys: [backend-build]
       - run:
           name: Back-end build
           command: |
-            # Your code here
-            exit 1
+             # Your code here
+             exit 1
       - save_cache:
-          paths:
-            - backend/node_modules
+          paths: [backend/node_modules]
           key: backend-build
   test-frontend:
     docker:
       - image: circleci/node:13.8.0
-    steps: null
+    steps:
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here              
   test-backend:
     docker:
       - image: circleci/node:13.8.0
-    steps: null
+    steps:
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
   scan-frontend:
     docker:
       - image: circleci/node:13.8.0
-    steps: null
+    steps:
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
   scan-backend:
     docker:
       - image: circleci/node:13.8.0
-    steps: null
+    steps:
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
   deploy-infrastructure:
     docker:
-      - image: circleci/node:13.8.0
+      - image: circleci/node:13.8.0 that supports AWS CLI
     steps:
+      # Checkout code from git
       - run:
           name: Ensure back-end infrastructure exists
           command: |
@@ -119,10 +124,15 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
+      # Here's where you will add some code to rollback on failure      
+
   configure-infrastructure:
     docker:
-      - image: circleci/node:13.8.0
+      - image: circleci/node:13.8.0 that supports Ansible
     steps:
+      # Checkout code from git
+      # Add ssh keys with fingerprint
+      # attach workspace
       - run:
           name: Install dependencies
           command: |
@@ -133,10 +143,12 @@ jobs:
           command: |
             # Your code here
             exit 1
+      # Here's where you will add some code to rollback on failure      
   run-migrations:
     docker:
-      - image: circleci/node:13.8.0
+      - image: circleci/node:13.8.0 that supports NodeJS
     steps:
+      # Checkout code from git
       - run:
           name: Run migrations
           command: |
@@ -147,10 +159,12 @@ jobs:
           command: |
             # Your code here
             exit 1
+     # Here's where you will add some code to rollback on failure      
   deploy-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: circleci/node:13.8.0 that supports AWS CLI
     steps:
+      # Checkout code from git
       - run:
           name: Install dependencies
           command: |
@@ -165,10 +179,14 @@ jobs:
           name: Deploy frontend objects
           command: |
             # your code here
+      # Here's where you will add some code to rollback on failure      
   deploy-backend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: circleci/node:13.8.0 that supports Ansible
     steps:
+      # Checkout code from git
+      # Add ssh keys with fingerprint
+      # attach workspace
       - run:
           name: Install dependencies
           command: |
@@ -177,9 +195,12 @@ jobs:
           name: Deploy backend
           command: |
             # your code here
+      # Here's where you will add some code to rollback on failure  
   smoke-test:
-    docker: null
+    docker:
+      # Lightweight Docker image 
     steps:
+      # Checkout code from git
       - run:
           name: Install dependencies
           command: |
@@ -196,10 +217,12 @@ jobs:
           name: Frontend smoke test.
           command: |
             # your code here
+      # Here's where you will add some code to rollback on failure  
   cloudfront-update:
     docker:
-      - image: circleci/node:13.8.0
+      - image: circleci/node:13.8.0 that supports AWS CLI
     steps:
+      # Checkout code from git
       - run:
           name: Install dependencies
           command: |
@@ -208,69 +231,55 @@ jobs:
           name: Update cloudfront distribution
           command: |
             # your code here
+      # Here's where you will add some code to rollback on failure  
 cleanup:
-  docker:
-    - image: circleci/node:13.8.0
-  steps:
-    - run:
-        name: Get old stack workflow id
-        command: |
-          # your code here
-          export OldWorkflowID="the id here"
-          export STACKS=[] #put the list of stacks here
-    - run:
-        name: Remove old stacks and files
-        command: |
-          if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-          then
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - run:
+          name: Get old stack workflow id
+          command: |
             # your code here
-          fi
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
+      - run:
+          name: Remove old stacks and files
+          command: |
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              # your code here
+            fi
+
 workflows:
   default:
     jobs:
       - build-frontend
       - build-backend
       - test-frontend:
-          requires:
-            - build-frontend
+          requires: [build-frontend]
       - test-backend:
-          requires:
-            - build-backend
+          requires: [build-backend]
       - scan-backend:
-          requires:
-            - build-backend
+          requires: [build-backend]
       - scan-frontend:
-          requires:
-            - build-frontend
+          requires: [build-frontend]
       - deploy-infrastructure:
-          requires:
-            - test-frontend
-            - test-backend
-            - scan-frontend
-            - scan-backend
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
-            branches: null
-            only:
-              - test-feature-branch
+            branches:
+              only: [test-feature-branch]
       - configure-infrastructure:
-          requires:
-            - deploy-infrastructure
+          requires: [deploy-infrastructure]
       - run-migrations:
-          requires:
-            - configure-infrastructure
+          requires: [configure-infrastructure]
       - deploy-frontend:
-          requires:
-            - run-migrations
+          requires: [run-migrations]
       - deploy-backend:
-          requires:
-            - run-migrations
+          requires: [run-migrations]
       - smoke-test:
-          requires:
-            - deploy-backend
-            - deploy-frontend
+          requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
-          requires:
-            - smoke-test
+          requires: [smoke-test]
       - cleanup:
-          requires:
-            - cloudfront-update
+          requires: [cloudfront-update]
